#Google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Import libary

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

#Read csv file

In [ ]:
df = pd.read_csv("kospi 200 2022 2023 2024.csv")

In [ ]:
df.head()

,date,closing price,market price,high price,low price,volume_M,change
0,2024-12-30,317.82,318.13,322.20,316.94,73.58M,-0.38%
1,2024-12-27,319.03,320.24,321.30,316.91,86.74M,-0.75%
2,2024-12-26,321.45,324.48,324.48,321.42,92.61M,-0.60%
3,2024-12-24,323.39,324.11,324.50,321.86,78.51M,0.13%
4,2024-12-23,322.98,321.00,324.00,319.77,100.61M,1.46%

In [ ]:
df['date'] = pd.to_datetime(df['date'])
unique_years = df['date'].dt.year.unique()
unique_years

array([2024, 2023, 2022], dtype=int32)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 718 entries, 0 to 717
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           718 non-null    datetime64[ns]
 1   closing price  718 non-null    float64
 2   market price   718 non-null    float64
 3   high price     718 non-null    float64
 4   low price      718 non-null    float64
 5   volume_M       718 non-null    object
 6   change         718 non-null    object
dtypes: datetime64[ns](1), float64(4), object(2)
memory usage: 39.4+ KB

#Change object data -> int data

**1. datatime**

In [ ]:
df['date'] = pd.to_datetime(df['date'])
print(f"orginal date' column type: {df['date'].dtype}")

df['y'] = df['date'].dt.year
df['m'] = df['date'].dt.month
df['d'] = df['date'].dt.day

print(f"'y' column type: {df['y'].dtype}")
print(f"'m' column type: {df['m'].dtype}")
print(f"'d' column type: {df['d'].dtype}")

existing_columns = df.columns.tolist()
for col in ['y', 'm', 'd']:
    if col in existing_columns:
        existing_columns.remove(col)

new_column_order = ['y', 'm', 'd'] + existing_columns
df = df[new_column_order]

orginal date' column type: datetime64[ns]
'y' column type: int32
'm' column type: int32
'd' column type: int32

In [ ]:
df.drop(columns=['date'], inplace=True)

In [ ]:
df.head()

,y,m,d,closing price,market price,high price,low price,volume_M,change
0,2024,12,30,317.82,318.13,322.20,316.94,73.58M,-0.38%
1,2024,12,27,319.03,320.24,321.30,316.91,86.74M,-0.75%
2,2024,12,26,321.45,324.48,324.48,321.42,92.61M,-0.60%
3,2024,12,24,323.39,324.11,324.50,321.86,78.51M,0.13%
4,2024,12,23,322.98,321.00,324.00,319.77,100.61M,1.46%

**2. volumn(M)**

In [ ]:
df['volume_M'] = df['volume_M'].str.replace('M', '', regex=False)
df['volume_M'] = df['volume_M'].str.replace('K', '', regex=False)
df['volume_M'] = df['volume_M'].astype(float)

**3. change %**

In [ ]:
df['change'] = df['change'].str.replace('%', '', regex=False)
df['change'] = df['change'].astype(float)

In [ ]:
df.describe().round(2)

,y,m,d,closing price,market price,high price,low price,volume_M,change
count,718.00,718.00,718.0,718.00,718.00,718.00,718.00,718.00,718.00
mean,2023.02,6.64,16.0,337.74,338.02,339.82,335.78,135.06,-0.01
std,0.81,3.37,8.7,23.08,23.06,23.05,23.05,44.74,1.19
min,2022.00,1.00,1.0,281.36,281.75,284.35,278.39,65.66,-9.12
25%,2022.00,4.00,8.0,320.83,321.12,322.90,318.66,108.37,-0.70
50%,2023.00,7.00,16.0,337.30,337.56,338.92,335.59,127.02,-0.01
75%,2024.00,10.00,23.0,355.40,355.18,356.76,352.75,151.02,0.72
max,2024.00,12.00,31.0,398.52,398.82,400.31,396.69,622.95,5.00

In [ ]:
df.isna().sum()

y                0
m                0
d                0
closing price    0
market price     0
high price       0
low price        0
volume_M         0
change           0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 718 entries, 0 to 717
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   y              718 non-null    int32
 1   m              718 non-null    int32
 2   d              718 non-null    int32
 3   closing price  718 non-null    float64
 4   market price   718 non-null    float64
 5   high price     718 non-null    float64
 6   low price      718 non-null    float64
 7   volume_M       718 non-null    float64
 8   change         718 non-null    float64
dtypes: float64(6), int32(3)
memory usage: 42.2 KB

#save dataset

In [ ]:
output_folder = '/content/drive/MyDrive/dataset'
output_filename = 'kospi200_cleaned_data.csv'

output_filepath = f"{output_folder}/{output_filename}"

df.to_csv(output_filepath, index=False, encoding='utf-8-sig')