#Goggle drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#Read csv

#Positive articles

In [ ]:
import pandas as pd

**이유는 모르겠지만 utf-8에서 깨짐이 발생해 cp949(window 기본 인코딩)을 사용했습니다.**

In [ ]:
file_name = 'NewsResult_20220127-20241231_pos.csv'
df = pd.read_csv(file_name,encoding='cp949')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   뉴스 식별자             20000 non-null  float64
 1   일자                 20000 non-null  int64
 2   언론사                20000 non-null  object
 3   기고자                19718 non-null  object
 4   제목                 20000 non-null  object
 5   통합 분류1             20000 non-null  object
 6   통합 분류2             18841 non-null  object
 7   통합 분류3             16353 non-null  object
 8   사건/사고 분류1          1677 non-null   object
 9   사건/사고 분류2          241 non-null    object
 10  사건/사고 분류3          43 non-null     object
 11  인물                 14060 non-null  object
 12  위치                 17808 non-null  object
 13  기관                 19981 non-null  object
 14  키워드                20000 non-null  object
 15  특성추출(가중치순 상위 50개)  20000 non-null  object
 16  본문                 20000 non-null  object
 17  URL                20000 non-null  object
 18  분석제외 여부            911 non-null    object
dtypes: float64(1), int64(1), object(17)
memory usage: 2.9+ MB

In [ ]:
df.drop(columns=[
    '뉴스 식별자',
    '언론사',
    '기고자',
    '통합 분류1',
    '통합 분류2',
    '통합 분류3',
    '사건/사고 분류1',
    '사건/사고 분류2',
    '사건/사고 분류3',
    '인물',
    '위치',
    '기관',
    '특성추출(가중치순 상위 50개)',
    'URL',
    '분석제외 여부'], inplace=True)

In [ ]:
df_sorted_by_date = df.sort_values(by='일자', ascending=False)
df_pos = df_sorted_by_date.drop_duplicates(subset=['제목'], keep='first')

df_pos.head()

,일자,제목,키워드,본문
31,20241231,"함영주 하나금융 회장, 자사주 5천주 매입 ""밸류업 박차 가할 것""","회장,함영주,금융,자사,매입,밸류업,박차,회장,함영주,금융,그룹,금융,경영진,자사주...",[머니투데이 이병권 기자] \n함영주 하나금융그룹 회장을 비롯한 하나금융 주요 경영...
14,20241231,10년간 6번 연초 효과 내년에도 통할까,"10년,효과,연초,내년,증시,전망,금리,전망,연초,코스피,항뱡,좌우,두각,연초,효과...",[이데일리 김응태 기자] 최근 10년 동안 코스피 지수가 1월에 플러스(+) 수익률...
15,20241231,비트코인 투기 때문에 한국 증시 폭락? “양의 상관관계 깨졌다”,"비트,코인,투기,폭락,한국,증시,상관관계,은행,파산,비트코인,투자자,자금,주식시장,...",은행 파산 속 값 오른 비트코인 [연합]\n \n\n[헤럴드경제=김보영 기자] 국내...
17,20241231,기업공시[12월 31일],"기업공시,12월,31일,코스피,공시,삼성에스디에스,삼성전자,한신공영,규모,ITO,서...",<코스피 공시> \n \n\n ▲삼성에스디에스(018260)=삼성전자(005930)...
51,20241231,"삼성전자, 레인보우로보틱스 최대주주로 미래로봇 개발 가속화","삼성전자,레인보우로보틱스,최대,주주,미래로봇,가속,2670억,추가,투자,확보,지분,...",약 2670억원 추가 투자해 지분 35.0% 확보 \nAI 이어 로봇 회사까지 대형...

In [ ]:
df_pos = df_pos[~df_pos['제목'].str.contains('<오늘의 인사>|기업공시', na=False)]

df_pos.drop(columns=['일자'], inplace=True)

/tmp/ipython-input-15-70087830.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pos.drop(columns=['일자'], inplace=True)

In [ ]:
df_pos.head()

,제목,키워드,본문
31,"함영주 하나금융 회장, 자사주 5천주 매입 ""밸류업 박차 가할 것""","회장,함영주,금융,자사,매입,밸류업,박차,회장,함영주,금융,그룹,금융,경영진,자사주...",[머니투데이 이병권 기자] \n함영주 하나금융그룹 회장을 비롯한 하나금융 주요 경영...
14,10년간 6번 연초 효과 내년에도 통할까,"10년,효과,연초,내년,증시,전망,금리,전망,연초,코스피,항뱡,좌우,두각,연초,효과...",[이데일리 김응태 기자] 최근 10년 동안 코스피 지수가 1월에 플러스(+) 수익률...
15,비트코인 투기 때문에 한국 증시 폭락? “양의 상관관계 깨졌다”,"비트,코인,투기,폭락,한국,증시,상관관계,은행,파산,비트코인,투자자,자금,주식시장,...",은행 파산 속 값 오른 비트코인 [연합]\n \n\n[헤럴드경제=김보영 기자] 국내...
51,"삼성전자, 레인보우로보틱스 최대주주로 미래로봇 개발 가속화","삼성전자,레인보우로보틱스,최대,주주,미래로봇,가속,2670억,추가,투자,확보,지분,...",약 2670억원 추가 투자해 지분 35.0% 확보 \nAI 이어 로봇 회사까지 대형...
50,[2024년 핫이슈 기업] 경영권 분쟁에 75년 동업 ‘종착역’ 재계 지각변동,"경영,분쟁,종착역,동업,재계,지각변동,국가기간산업,미래,충돌,창업주,일가,사모펀드,...",국가기간산업-미래 신산업 ‘충돌’ \n\n창업주 일가-사모펀드 극한 대립 \n\n지...

In [ ]:
df_pos['content'] = df_pos['제목'].astype(str) + ' ' + df_pos['키워드'].astype(str) + ' ' + df_pos['본문'].astype(str)

In [ ]:
df_pos.drop(columns=['제목','키워드','본문'], inplace=True)

In [ ]:
df_pos.head()

                                              content
31  함영주 하나금융 회장, 자사주 5천주 매입 "밸류업 박차 가할 것" 회장,함영주,금...
14  10년간 6번 연초 효과 내년에도 통할까 10년,효과,연초,내년,증시,전망,금리,전...
15  비트코인 투기 때문에 한국 증시 폭락? “양의 상관관계 깨졌다” 비트,코인,투기,폭...
51  삼성전자, 레인보우로보틱스 최대주주로 미래로봇 개발 가속화 삼성전자,레인보우로보틱스...
50  [2024년 핫이슈 기업] 경영권 분쟁에 75년 동업 ‘종착역’ 재계 지각변동 경영...

In [ ]:
df_pos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19673 entries, 31 to 19983
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   content  19673 non-null  object
dtypes: object(1)
memory usage: 307.4+ KB

#Negative articles

In [ ]:
file_name = 'NewsResult_20220127-20241231_neg.csv'
df = pd.read_csv(file_name,encoding='cp949')

In [ ]:
df.drop(columns=[
    '뉴스 식별자',
    '언론사',
    '기고자',
    '통합 분류1',
    '통합 분류2',
    '통합 분류3',
    '사건/사고 분류1',
    '사건/사고 분류2',
    '사건/사고 분류3',
    '인물',
    '위치',
    '기관',
    '특성추출(가중치순 상위 50개)',
    'URL',
    '분석제외 여부'], inplace=True)

In [ ]:
df_sorted_by_date = df.sort_values(by='일자', ascending=False)
df_neg = df_sorted_by_date.drop_duplicates(subset=['제목'], keep='first')

df_neg.head()

,일자,제목,키워드,본문
13,20241231,<오늘의 인사>,"인사,KPI,승진,산업,에디터,박철응,부국장,충남일보,충남본사,천안,사장,유근재,신...",◇KPI뉴스 △승진 ▷산업에디터 박철응(부국장) \n? \n◇충남일보 ▷충남본사(천...
14,20241231,다시 꺾인 거래량 개인 외인 '5조' 미련 없이 던졌다 [2024 증시 결산],"거래량,개인,외인,5조,미련,결산,증시,거래,증시,마감,이달,증시,거래량,감소세,개...",전날 올해의 국내 증시 거래가 마감한 가운데 이달 증시 거래량이 다시 감소세로 돌아...
15,20241231,내년에는 건설주 좋아지나? 저가매수를 고려 중이었다면,"내년,건설주,저가매수,스탁론,관심,투자기회,투자자들,주식매입,자금,활용,스탁론,눈길...","한편, 스탁론에 대한 관심이 날로 높아지고 있다. 모처럼 잡은 투자기회를 놓치지 않..."
20,20241231,올해 세계 주식 20% 올랐다 주요 국가 중 한국만 ‘역주행’,"20%,세계,주식,20%,국가,한국,역주행,MSCI,세계,주식,지수,122조,달러,...",MSCI 전 세계 주식지수 \n올해 122조달러에 육박 \nGDP 톱 20중 13개...
21,20241231,"""환율 1500원, 외환위기 또 온다"" KDI의 의아한 경고 [금융당국 포커스]","환율,외환위기,KDI,의아,포커스,경고,금융,당국,다수,신흥국,환율방어,외환보유액,...","""다수의 신흥국에서 환율방어를 위해 외환보유액을 소진하다가 외환위기가 발생했다."" ..."

In [ ]:
df_neg = df_neg[~df_neg['제목'].str.contains('<오늘의 인사>|기업공시', na=False)]

df_neg.drop(columns=['일자'], inplace=True)

/tmp/ipython-input-24-2327930864.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neg.drop(columns=['일자'], inplace=True)

In [ ]:
df_neg['content'] = df_neg['제목'].astype(str) + ' ' + df_neg['키워드'].astype(str) + ' ' + df_neg['본문'].astype(str)

In [ ]:
df_neg.drop(columns=['제목','키워드','본문'], inplace=True)

In [ ]:
df_neg.head()

                                              content
14  다시 꺾인 거래량 개인 외인 '5조' 미련 없이 던졌다 [2024 증시 결산] 거래...
15  내년에는 건설주 좋아지나? 저가매수를 고려 중이었다면 내년,건설주,저가매수,스탁론,...
20  올해 세계 주식 20% 올랐다 주요 국가 중 한국만 ‘역주행’ 20%,세계,주식,2...
21  "환율 1500원, 외환위기 또 온다" KDI의 의아한 경고 [금융당국 포커스] 환...
22  2차전지 지고 금융 바이오株 뜨고 코스피 시총 톱10 격변 [2024 주식시장 결산...

In [ ]:
df_neg.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19783 entries, 14 to 19992
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   content  19783 non-null  object
dtypes: object(1)
memory usage: 309.1+ KB

#Combine

In [ ]:
import torch
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments, AutoModel
from torch.utils.data import Dataset
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

**Label ebcidubg**

In [ ]:
text_column_name = 'content'

df_pos['label'] = 1

df_neg['label'] = 0

**Mix data**

In [ ]:
combined_df = pd.concat([df_pos, df_neg]).sample(frac=1, random_state=42).reset_index(drop=True)

**get(0,0)} : used to express '0' even values without**

In [ ]:
all_texts = combined_df[text_column_name].tolist()
all_labels = combined_df['label'].tolist()

print(f"Number of Total data: {len(all_texts)}")
print(f"Pos Lable ({combined_df['label'].value_counts().get(1, 0)}), Neg Lable ({combined_df['label'].value_counts().get(0, 0)})")

Number of Total data: 39456
Pos Lable (19673), Neg Lable (19783)

**Verification : Data for interim checks used to prevent overfitting**

In [ ]:
train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    all_texts, all_labels, test_size=0.2, random_state=42, stratify=all_labels
)

val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts, temp_labels, test_size=0.5, random_state=42, stratify=temp_labels
)

In [ ]:
print(f"Number of Train data : {len(train_texts)}")
print(f"Number of Validation data: {len(val_texts)}")
print(f"Number of Test data: {len(test_texts)}")

Number of Train data : 31564
Number of Validation data: 3946
Number of Test data: 3946

#Load tokenizer and model

https://klue-benchmark.com/

https://medium.com/@kanghee.lee/klue-korean-language-understanding-evaluation-d06850888d41

**A standard benchmark dataset and framework for systematically evaluating and comparing the performance of various Korean NLP models, including KoBERT**

In [ ]:
MODEL_NAME = "klue/bert-base"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/289 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/425 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

**num_labels : Positives and negatives '2'**

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

model.safetensors:   0%|          | 0.00/445M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at klue/bert-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

#Define custom dataset classes

In [ ]:
class StockSentimentDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

#Text Preprocessing

In [ ]:
train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=512)
val_encodings = tokenizer(val_texts, truncation=True, padding=True, max_length=512)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=512)

train_dataset = StockSentimentDataset(train_encodings, train_labels)
val_dataset = StockSentimentDataset(val_encodings, val_labels)
test_dataset = StockSentimentDataset(test_encodings, test_labels)

# Calculate Evaluation Indicators for Binary Classification

In [ ]:
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)

    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

In [ ]:
output_dir = '/content/drive/MyDrive/analysis'

#Training Configuration

In [ ]:
training_args = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=50,
    weight_decay=0.01,
    learning_rate=5e-5,
    logging_dir='./logs',
    logging_strategy='steps',
    logging_steps=50,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='f1',
    greater_is_better=True,
    dataloader_num_workers=4,
    seed=42
)

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,    #Prevent overfit
    compute_metrics=compute_metrics,
)

# Use the api key to show visualization using 'WANDB'

**원래 목표는 wandb를 사용해 학습을 시각화로 나타내려고 하였으나 시간이 많이 걸리는 문제로 간단하게 vs code에서 학습만 시키는 단계를 사용하였습니다**

In [ ]:
trainer.train()
print("--- KoBERT Train completion ---")

/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: pjh04100 (pjh04100-gachon-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(

KeyboardInterrupt:

#Save model and token

In [ ]:
model_save_path = "/content/drive/MyDrive/kobert_model"
trainer.save_model(model_save_path)

In [ ]:
tokenizer.save_pretrained(model_save_path)

('/content/drive/MyDrive/kobert_model/tokenizer_config.json',
 '/content/drive/MyDrive/kobert_model/special_tokens_map.json',
 '/content/drive/MyDrive/kobert_model/vocab.txt',
 '/content/drive/MyDrive/kobert_model/added_tokens.json',
 '/content/drive/MyDrive/kobert_model/tokenizer.json')

#Test and result

In [ ]:
test_results = trainer.evaluate(test_dataset)
test_results

/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(

{'eval_loss': 0.03766634687781334,
 'eval_accuracy': 0.9899497487437185,
 'eval_f1': 0.98989898989899,
 'eval_precision': 0.98989898989899,
 'eval_recall': 0.98989898989899,
 'eval_runtime': 5.8154,
 'eval_samples_per_second': 34.219,
 'eval_steps_per_second': 2.235,
 'epoch': 5.0}

In [ ]:
try:
    loaded_tokenizer = AutoTokenizer.from_pretrained(model_save_path)
    loaded_model = AutoModelForSequenceClassification.from_pretrained(model_save_path)
except Exception as e:
    print(f"Err: {e}")
    exit()